pipeline {
    agent any
    tools {
        maven 'maven-3.6.3' 
    }
    environment {
        DATE = new Date().format('yy.M')
        TAG = "${DATE}.${BUILD_NUMBER}"
    }
    stages {
        stage ('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Docker Build') {
            steps {
                script {
                    docker.build("vigneshsweekaran/hello-world:${TAG}")
                }
            }
        }
        stage('Pushing Docker Image to Dockerhub') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker_credential') {
                        docker.image("vigneshsweekaran/hello-world:${TAG}").push()
                        docker.image("vigneshsweekaran/hello-world:${TAG}").push("latest")
                    }
                }
            }
        }
        stage('Deploy'){
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'vm_key', keyFileVariable: 'SSH_PRIVATE_KEY_PATH')]) {
                    echo "$SSH_PRIVATE_KEY_PATH"
                    sh "ssh -i $SSH_PRIVATE_KEY_PATH ubuntu@dayal-test.letspractice.tk pwd"
                }
                sh "docker stop hello-world | true"
                sh "docker rm hello-world | true"
                sh "docker run --name hello-world -d -p 9004:80 vigneshsweekaran/hello-world:${TAG}"
            }
        }
    }
}
